### PR TITLE
feat(modal): trap focus in opend modal

### PR DESCRIPTION
**Pull request by Yelinz**

### CODE REVIEW

**Comment by Yelinz** [comment]
> 
> 
> Could you add a test for this? 😁

I'll try

**Comment by Yelinz** [comment]
@anehx It doesn't seem like you can simulate a Tab key press in the tests.

**Comment by anehx** [comment]
@Yelinz sure you could (`triggerKeyEvent(".modal-body", "keypress", 9)`, https://github.com/emberjs/ember-test-helpers/blob/master/API.md#triggerkeyevent) however I meant just checking whether the focus is on the right element after opening the modal

**Comment by Yelinz** [comment]
triggerKeyEvent doesnt move the focus, it just tries to execute the event

**Comment by Yelinz** [comment]
When opening the modal there is no specific focus

**Pull request merged**
