### PR TITLE
fix(deps): move focus-trap to dependencies

### PR DESCRIPTION
**Pull request by fkm**
Otherwise, it will be missing in the project.

### CODE REVIEW

**Comment by fkm** [comment]
CC @czosel @anehx

**Comment by czosel** [comment]
Tests are failing, same issue as in ember-caluma:
```
not ok 5 Chrome 80.0 - [undefined ms] - Global error: Uncaught TypeError: Ember.assert is not a function at http://localhost:7357/161550045327/tests/index.html?hidepassed, line 37
```

**Comment by czosel** [comment]
@fkm can you rebase?

**Pull request merged**
