### PR TITLE
chore: upgrade dependencies incl. uikit, pin focus-trap

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Comment by czosel** [comment]
Does anyone see why codecov fails?

**Comment by fkm-adfinis** [comment]
Not sure. Could there be a configuration that disallows large decreases in coverage?

**Review by fkm-adfinis — APPROVED** [review]

**Comment by anehx** [comment]
Please update the versions in `package.json` as well... Also, you're aware that resolutions only fix the dummy app, right? Isn't this something that we should fix for the users of this addon as well?

**Comment by fkm-adfinis** [comment]
> Also, you're aware that resolutions only fix the dummy app, right? Isn't this something that we should fix for the users of this addon as well?

I didn't know. And I agree.

**Comment by anehx** [comment]
Superseeded by #651

**Pull request closed without merging**
