### PR TITLE
fix(modal): correctly resolve root element for embedded apps

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Review by anehx — COMMENTED** [review]
Your tests are failing :grin: 

https://giphy.com/gifs/simpsons-nelson-the-RG3lm5VlrbDV7YNana

**Comment by czosel** [comment]
puh, the failure looks like it's unrelated to my change, right?

**Comment by anehx** [comment]
Yes :man_shrugging:

**Comment by Yelinz** [comment]
Rebase and it should work now

**Review by anehx — APPROVED** [review]

**Pull request merged**
